[package]
name = "lan_rs_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
df = ["polars"]
use_ndarray = ["ndarray", "ndarray-linalg"]

[dependencies]
bitflags = "2.8.0"
derive_builder = "0.20.2"
generator = "0.8.4"
ibig = "0.3.6"
im = "15.1.0"
itertools = "0.14.0"
libm = "0.2.11"
log = "0.4.25"
petgraph = "0.7.1"
petgraph-evcxr = "0.2.0"
plotters = "0.3.7"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
rpds = "1.1.0"
tap = "1.0.1"

polars = { version = "0.46.0", features = ["lazy"], optional = true}

ndarray = { version = "0.16.1", optional = true}
ndarray-linalg = { version = "0.16", features = ["openblas"], optional = true}

[dependencies.blas-src]
version = "0.9"
default-features = false
features = ["openblas"]
